### ISSUE TITLE
Auto Closing Brackets

### ISSUE THREAD

**Issue by heiehi-go** [MathieuMoalic/vscode-mx3#1]
Hi there!
thank you for your works on this extension. it helps me a lot!
but I found it cannot use auto closing brackets. is there any solution to solve this?

**Comment by MathieuMoalic** [comment]
Hey :)
Indeed it is not working by default in .mx3 files. I will try to fix but for now you can set it to "Always" in the settings.
![image](https://github.com/MathieuMoalic/vscode-mx3/assets/21007252/d752ec22-1436-4b00-bc3d-d6617c77da37)

**Comment by MathieuMoalic** [comment]
The new version 1.1.2 has auto closing brackets now. It was quite easy to add. Thanks for the great suggestion!
